### ISSUE TITLE
Crabs crash on serverside

### ISSUE THREAD

**Issue by nocturni** [SirSquidly/Oceanic-Expanse#89] opened 2024-07-20 22:21 UTC
https://pastebin.com/xa2ThqCW

**Comment by SirSquidly** [comment] 2024-07-21 00:31
This is a duplicate of https://github.com/SirSquidly/Oceanic-Expanse/issues/85, so it is known already. I will close this issue.

**Closed as completed by SirSquidly** 2024-07-21 00:31 UTC
Labels: bug, duplicate

**Comment by nocturni** [comment] 2024-07-22 16:03
my bad! didn't see
