### ISSUE TITLE
Disabling Pickled Heads causes server to not start

### ISSUE THREAD

**Issue by Boffinbox** [SirSquidly/Oceanic-Expanse#87] opened 2024-07-15 08:43 UTC
**Description**
When launching any forge server with OE, disabling pickled heads in the config (`enablePickledHead=false`) causes the server to not start. This has been tried in a fresh 1.12.2 forge server (v2859) with no other mods, just OE and the required MixinBooter dependency.

**Steps to reproduce**
1. Install a fresh forge 1.12.2 server, accept eula, etc etc.
2. Add OE and MixinBooter jars, then start server to generate config.
3. Set OE config variable `enablePickledHead` from default value `true` to value `false`.
4. Launch your server.

**Additional Files**
[crash-2024-07-15_09.22.15-server.txt](https://github.com/user-attachments/files/16232023/crash-2024-07-15_09.22.15-server.txt)

Thanks for looking into this 🙂

**Comment by SirSquidly** [comment] 2024-07-15 18:38
A quick investigation shows this is caused by [Line 278 ](https://github.com/SirSquidly/Oceanic-Expanse/blob/master/src/main/java/com/sirsquidly/oe/init/OEBlocks.java#L278)of 'OEBlocks', the Pickled Head uses a special ItemBlock, and thus is manually registered, but I forgot a basic check. 

Should be a very quick fix.

**Comment by SirSquidly** [comment] 2024-07-21 01:14
Fixed in 1.1.3

**Closed as completed by SirSquidly** 2024-07-21 01:14 UTC
Labels: bug
