### ISSUE TITLE
Drowned spawning breaking due to Biome Tweaker

### ISSUE THREAD

**Issue by Coder-Relri** [SirSquidly/Oceanic-Expanse#90] opened 2024-07-22 07:51 UTC
I'm currently working on a modpack and it seems that biome tweaker is causing Drowned spawning to break and causing a lot of them to spawn in rivers.

I'm using Oceanic-Expanse (1.1.3), BiomeTweaker (BiomeTweaker-1.12.2 3.2.369) and BiomeTweakerCore (BiomeTweakerCore-1.12.2 1.0.39)

The forge launcher I'm using is 14.23.5.2860.

![image](https://github.com/user-attachments/assets/fa48e555-0370-4730-a69c-12a3d29f027e)

**Comment by SirSquidly** [comment] 2024-07-25 16:34
Yep, Drowned Spawns always seem to act funky. I'll try and add a hacky fix for it in the next bug fix update.

**Comment by SirSquidly** [comment] 2024-08-12 18:11
I have included a semi-fix in 1.1.4, which should prevent endless spawning of Drowned when mods like BiomeTweaker or RandomTweaks are installed.

This is not a full fix, as the spawning *will* be slightly higher than the intended rate, but it will not be overblown rates. I will work on a possible fix for this more in the future.

**Comment by SirSquidly** [comment] 2024-11-13 08:06
Since there has been no followup on this issue for multiple months, I assume the issue is resolved. If this re-occurs, please open a new issue.

**Closed as completed by SirSquidly** 2024-11-13 08:06 UTC
Labels: bug, bug from another mod
