### ISSUE TITLE
1.12.2 - Description: Ticking entity - java.lang.NoSuchMethodError: com.sirsquidly.oe.entity.EntityCrab.isPartying()Z at com.sirsquidly.oe.entity.EntityCrab.func_70636_d(EntityCrab.java:170)

### ISSUE THREAD

**Issue by Nightreaver** [SirSquidly/Oceanic-Expanse#88] opened 2024-07-17 12:34 UTC
**Description**

The server ist crashing, sadly during/after world generation near ocean with `OceanicExpanse-1.1.2.jar`.
Yet not have disabled other mods, let me know if its required as it might come from mod interaction.

* Modpack (custom/private) 
* so far only happens on linux(docker) server - couldnt replicate on windows
* the issue might be related to the `is.Remote` section, as it only happens when i connect to remote server, not when running local (or its linux issue) 
https://github.com/SirSquidly/Oceanic-Expanse/blob/6d749b490310aba76508c919492a1321bb6e31ab/src/main/java/com/sirsquidly/oe/entity/EntityCrab.java#L172

```
java.lang.NoSuchMethodError: com.sirsquidly.oe.entity.EntityCrab.isPartying()Z
	at com.sirsquidly.oe.entity.EntityCrab.func_70636_d(EntityCrab.java:170)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

**Additional Files**
Always include relevant Logs! This can include normal or Crashlogs, found in their respective folders. If the issue relates to visuals in anyway, Screenshots will be very helpful and appreciated.
[crash-2024-07-17_12.28.30-server.txt](https://github.com/user-attachments/files/16265581/crash-2024-07-17_12.28.30-server.txt)
[crash-2024-07-17_12.20.03-server.txt](https://github.com/user-attachments/files/16265582/crash-2024-07-17_12.20.03-server.txt)

**Workaround**

Disable crab in config

**Comment by SirSquidly** [comment] 2024-07-17 17:31
Actually, I think the issue might be that [Line 170](https://github.com/SirSquidly/Oceanic-Expanse/blob/6d749b490310aba76508c919492a1321bb6e31ab/src/main/java/com/sirsquidly/oe/entity/EntityCrab.java#L170) is checking the `isPartying` variable, which I left as ClientSide Only.

https://github.com/SirSquidly/Oceanic-Expanse/blob/6d749b490310aba76508c919492a1321bb6e31ab/src/main/java/com/sirsquidly/oe/entity/EntityCrab.java#L136

I am almost certain that is the oversight.

**Comment by SirSquidly** [comment] 2024-07-17 17:42
Also, this is a duplicate of #85, so I will close it. Thank you for the additional information though.

**Closed as completed by SirSquidly** 2024-07-17 17:42 UTC
Labels: bug, duplicate
