### ISSUE TITLE
Drowned Ticking entity - [Edit: Special AI issue]

### ISSUE THREAD

**Issue by Sereath** [SirSquidly/Oceanic-Expanse#19] opened 2023-05-09 06:57 UTC
Oceanic Expanse paired with [Special AI](https://www.curseforge.com/minecraft/mc-mods/special-ai) triggered this:
```
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.pathfinding.PathNavigateSwimmer cannot be cast to net.minecraft.pathfinding.PathNavigateGround
    at fathertoast.specialai.ai.grief.EntityAIBreakDoorSpecial.findObstructingDoor(EntityAIBreakDoorSpecial.java:97)
    at fathertoast.specialai.ai.grief.EntityAIBreakDoorSpecial.shouldExecute(EntityAIBreakDoorSpecial.java:85)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:94)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45)
    at net.minecraft.entity.monster.EntityZombie.onLivingUpdate(EntityZombie.java:223)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at com.sirsquidly.oe.entity.EntityDrowned.onUpdate(EntityDrowned.java:154)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```
```
  Suspected Mods: Special AI (specialai), Oceanic Expanse (oe)
```
https://gist.github.com/Sereath/422a819107044a9b3ececa91291da3ae

They are not even included in the config for Special AI.

![image](https://user-images.githubusercontent.com/54506307/237018034-3453a4da-fac8-404c-85ba-4c9d4233c435.png)

The only thing I did was to go to the ocean a fly around in a new world after downloading and including this in our modpack. And unfortunately, if I go report this to Special AI's author Im just going to get blocked for even mentioning **1.12**.

**Comment by SirSquidly** [comment] 2023-05-09 08:03
I swear to- Special AI is not working as intended by its code?? [In the code](https://github.com/FatherToast/SpecialAI/blob/0fe4dc5f1cf240b7875ff1ad9a7a653fcf5afba1/src/main/java/fathertoast/specialai/config/util/EntityList.java#L116), it claims mobs not in the list will return false, which obviously isn't true, leading to this!

I can't think of an easy way to fix this on my end, so I'll have to add it to the [Compatibility List](https://github.com/SirSquidly/Oceanic-Expanse/wiki/Mod-Compatibilities) as incompatible, without tweaks.

Add `oe:drowned 0.0 oe:pickled 0.0` to the door breaking mob list in Special AI's config, that fixes the issue.

**Comment by SirSquidly** [comment] 2023-05-09 08:07
> And unfortunately, if I go report this to Special AI's author Im just going to get blocked for even mentioning **1.12**.

Looking at their closed issues shows they aren't against 1.12, they just don't support it. I'll open an issue on their tracker, just so others can know.

EDIT: [Opened said issue.](https://github.com/FatherToast/SpecialAI/issues/26)

**Comment by Sereath** [comment] 2023-05-09 08:39
Thank you for checking, adding the entities to the config that way worked.
And thank you for opening an issue over there.

**Comment by SirSquidly** [comment] 2023-05-28 21:05
I'm closing this issue for now, as far as I can see, this isn't something to be fixed on my end.

I'll also change the title from "Drowned Ticking entity" to "Drowned Ticking entity - [Edit: Special AI issue]" so any future users can more easily find information on this issue.

**Closed as completed by SirSquidly** 2023-05-28 21:05 UTC
Labels: bug from another mod
