### ISSUE TITLE
Shelly Sand doesn't actually require a shovel

### ISSUE THREAD

**Issue by xJon** [SirSquidly/Oceanic-Expanse#27] opened 2023-06-01 19:37 UTC
The player can just instantly break it with their hand, unlike what the wiki suggests.

**Comment by SirSquidly** [comment] 2023-06-04 10:04
Duplicate of [Issue 23](https://github.com/SirSquidly/Oceanic-Expanse/issues/23).

**Closed as completed by SirSquidly** 2023-06-04 10:04 UTC
Labels: duplicate
